name: "github-action-auto-release"
description: "Draft your next Release notes as Pull Requests are merged into main"
inputs:
  token:
    description: "Standard GitHub token (e.g., ${{ secrets.GITHUB_TOKEN }})"
    required: false
runs:
  using: "composite"
  steps:
    # Get PR from merged commit to master
    - uses: actions-ecosystem/action-get-merged-pull-request@v1
      id: get-merged-pull-request
      with:
        github_token: ${{ inputs.token }}
    # Drafts your next Release notes as Pull Requests are merged into "main"
    - uses: release-drafter/release-drafter@v5
      with:
        publish: ${{ !contains(steps.get-merged-pull-request.outputs.labels, 'no-release') }}
        prerelease: false
        config-name: auto-release.yml
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
